### ISSUE TITLE
Craft energy battery don't work

### ISSUE THREAD

**Issue by FabienChatton** [FabienChatton/RealmTech#9]
A shape craft with the inventory fill don't work
![image](https://github.com/FabienChatton/RealmTech/assets/117712563/64d72e37-aeab-4faf-b24a-c79b0764f92f)

![image](https://github.com/FabienChatton/RealmTech/assets/117712563/9efb32ef-9539-43fb-a795-c07d5c4fffab)

**Comment by Antoniofo** [comment]
isn't it realmtech.Items.EnergyCable and realmtech.Items.CopperIngot with capital i ?
